mitigate format-string vulnerability in syslog()
Fixes:
hdapsd fails to build if "-Werror=format-security" flag is used.
...
hdapsd.c:91:3: error: format not a string literal and no format arguments
[-Werror=format-security]

More info at: https://fedoraproject.org/wiki/Format-Security-FAQ